apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-service
    type: demo-voting-app
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: demo-voting-app
